---
# Example vars file for maintenance

lock:
  directory: /etc/node-maintenance/
  file: maintenance.lock

#Â Will look for scripts in ./roles/maintenance/files/scripts
scripts:
  directory: scripts
  target: /etc/

notification:
  slack: 
    enabled: true
    token: XXXX/YYYY/ZZZZ

